export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8 text-center">Terms of Service</h1>
      
      <div className="prose prose-lg dark:prose-invert mx-auto">
        <p className="text-slate-600 dark:text-slate-400 mb-8">
          Last updated: December 31, 2025
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">1. Acceptance of Terms</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            By accessing or using Career Advisor, you agree to be bound by these Terms of Service. 
            If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">2. Description of Service</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            Career Advisor is an AI-powered career planning tool that generates personalized 
            roadmaps to help users plan their professional development. The roadmaps are generated 
            using artificial intelligence and are intended for informational and planning purposes only.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">3. User Accounts</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            To access certain features, you may need to create an account. You are responsible for:
          </p>
          <ul className="list-disc pl-6 mt-4 space-y-2 text-slate-600 dark:text-slate-400">
            <li>Maintaining the confidentiality of your account credentials</li>
            <li>All activities that occur under your account</li>
            <li>Notifying us immediately of any unauthorized use</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">4. Acceptable Use</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            You agree not to:
          </p>
          <ul className="list-disc pl-6 mt-4 space-y-2 text-slate-600 dark:text-slate-400">
            <li>Use the service for any illegal purpose</li>
            <li>Attempt to gain unauthorized access to our systems</li>
            <li>Interfere with or disrupt the service</li>
            <li>Resell or redistribute our services without permission</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">5. Intellectual Property</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            The service and its original content, features, and functionality are owned by 
            Career Advisor and are protected by international copyright, trademark, and other 
            intellectual property laws.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">6. Disclaimer</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            The career roadmaps and recommendations provided by our service are generated by AI 
            and are for informational purposes only. We do not guarantee employment outcomes or 
            the accuracy of the recommendations. Users should use their own judgment and conduct 
            additional research when making career decisions.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">7. Limitation of Liability</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            In no event shall Career Advisor be liable for any indirect, incidental, special, 
            consequential, or punitive damages arising out of or relating to your use of the service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">8. Changes to Terms</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            We reserve the right to modify these terms at any time. We will notify users of 
            significant changes by posting a notice on our website or sending an email.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-slate-800 dark:text-slate-200">9. Contact</h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            For any questions about these Terms of Service, please contact us at:{' '}
            <a href="mailto:legal@careeradvisor.app" className="text-blue-600 hover:text-blue-800 dark:text-blue-400">
              legal@careeradvisor.app
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
